spring.datasource.url=jdbc:postgresql://localhost:5433/roomfindr
spring.datasource.username=roomfindr
spring.datasource.password=roomfindr

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true